Diagonal.exe: Diagonal.cs ../../CircuitSim/CircuitSim.dll
	mcs -out:Diagonal.exe Diagonal.cs -r:../../CircuitSim/CircuitSim.dll
	cp ../../CircuitSim/CircuitSim.dll .

clean:
	rm -f Diagonal.exe CircuitSim.dll
